package com.indev.claraa.helper

class Constant {
    companion object {
        val PREF_IS_LOGIN = "PREF_IS_LOGIN"
        val PREF_IS_UPDATE = "PREF_IS_UPDATE"
        val PREF_IS_CHECK_CART = "PREF_IS_CHECK_CART"
        val PREF_IS_CHECK_ORDER = "PREF_IS_CHECK_ORDER"
        val PREF_ADDRESS_ID = "PREF_ADDRESS_ID"
        val PREF_SPLASH= "PREF_SPLASH"
        val PREF_USERID = "PREF_USERID"
        val PREF_USER_NAME = "PREF_USER_NAME"
        val PREF_USER_EMAIL = "PREF_USER_EMAIL"
        val PREF_USER_MOBILE = "PREF_USER_MOBILE"
        val PREF_TOKEN = "PREF_TOKEN"
        val PREF_IS_FORGET = "PREF_FORGET"
        val PREF_STATEID = "PREF_STATEID"
        val PREF_DISTRICTID = "PREF_DISTRICTID"
        val PREF_PASSWORD = "PREF_PASSWORD"
        val PREF_CREDIT = "PREF_CREDIT"
        val PREF_ACTIVE = "PREF_ACTIVE"
        val PREF_APROVEL_ID = "PREF_APROVEL_ID"
        val PREF_LATITUDE= "PREF_LATITUDE"
        val PREF_LONGITUDE = "PREF_LONGITUDE"
        val PREF_NEWADDRESS = "PREF_NEWADDRESS"
        val PREF_PRODUCT_NAME = "PREF_PRODUCT_NAME"
        val PREF_PRODUCT_ID = "PREF_PRODUCT_ID"
        val PREF_PACKET_ID = "PREF_PACKET_ID"
        val PREF_PAYMENT_MODE = "PREF_PAYMENT_MODE"
        val PREF_CHECK_PAYMENT_TRANSCTAION = "PREF_CHECK_PAYMENT_TRANSCTAION"
        val GPS_CODE = 1002
    }
}